### ISSUE TITLE
`sudo -u username` uses system32 as current directory

### ISSUE THREAD

**Issue by sebthom** [chrisant996/sudo-windows#2]
When executing a command via sudo, the current working directory is not inherited instead system32 directory is used as workdir.

Example:
```batch
D:\> sudo cmd /c echo ^%CD^%
D:\

D:\> sudo -u myuser cmd /c echo ^%CD^%
C:\WINDOWS\system32
```

**Comment by chrisant996** [comment]
Only when using `-u`.  The `CreateProcessWithLogonW` API behaves differently than the rest of the process creation APIs.

**Comment by sebthom** [comment]
Nice, thanks for the quick fix!
